import json
import re
import subprocess
import argparse
import sys
import os

def get_blocks(page_id, token):
    cmd = f"curl -s \"https://api.notion.com/v1/blocks/{page_id}/children\" -H \"Authorization: Bearer {token}\" -H \"Notion-Version: 2022-06-28\""
    res = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if res.returncode != 0:
        print(f"Error fetching blocks: {res.stderr}")
        return []
    try:
        return json.loads(res.stdout).get("results", [])
    except json.JSONDecodeError:
        print("Error decoding JSON")
        return []

def delete_block(block_id, token):
    cmd = f"curl -s -X DELETE \"https://api.notion.com/v1/blocks/{block_id}\" -H \"Authorization: Bearer {token}\" -H \"Notion-Version: 2022-06-28\""
    subprocess.run(cmd, shell=True)

def main():
    parser = argparse.ArgumentParser(description="Clean Notion page from frontmatter/typo blocks (e.g. 'title: ...')")
    parser.add_argument("page_id", help="The ID of the Notion page to clean")
    args = parser.parse_args()

    token = os.environ.get("NOTION_API_TOKEN")
    if not token:
        # Try to load from .env
        if os.path.exists(".env"):
            with open(".env") as f:
                for line in f:
                    if "NOTION_API_TOKEN" in line:
                        token = line.split("=", 1)[1].strip().strip("\"'")
        if not token:
            print("NOTION_API_TOKEN not found in env or .env file.")
            sys.exit(1)

    print(f"Fetching blocks for page {args.page_id}...")
    blocks = get_blocks(args.page_id, token)
    
    to_delete = set()
    for i, b in enumerate(blocks):
        if b["type"] == "paragraph":
            rt = b["paragraph"].get("rich_text", [])
            text = "".join([x.get("plain_text", "") for x in rt]).strip()
            
            # Check if text is a metadata typo (e.g. 'title: Scoping', 'id: 1234')
            if re.match(r"^[a-z_]+:\s.*", text, re.IGNORECASE) or text == "---":
                print(f"Found frontmatter block {b['id']} -> '{text}'")
                to_delete.add(b["id"])
                
                # Delete adjacent dividers commonly generated by YAML frontmatter
                if i > 0 and blocks[i-1]["type"] == "divider":
                    to_delete.add(blocks[i-1]["id"])
                if i < len(blocks) - 1 and blocks[i+1]["type"] == "divider":
                    to_delete.add(blocks[i+1]["id"])
                
    deleted_count = 0
    for b_id in to_delete:
        print(f"Deleting block {b_id}")
        delete_block(b_id, token)
        deleted_count += 1
                
    print(f"Cleanup complete. Deleted {deleted_count} blocks.")

if __name__ == "__main__":
    main()
